In [1]:
import csv

from keras.models import Sequential
import tensorflow as tf

from keras.layers.core import Dense, Activation, Flatten
from keras.layers.convolutional import Convolution2D
from keras.optimizers import adam
from keras.utils import np_utils
from sklearn import metrics
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
import numpy as np
import random
from numpy import *

from tensorflow.keras.models import load_model

from keras import backend as K

from keras.layers import Conv2D
from sklearn.metrics import mean_squared_error

Using TensorFlow backend.


In [2]:
results = []
with open("dataset.csv") as csvfile:
    reader = csv.reader(csvfile, quoting=csv.QUOTE_NONNUMERIC)
    for row in reader:
        results.append(row)
        
results = np.array(results)
results[results < 0] = 0

print(results)

[[952. 959. 952. ...   0.   0.   0.]
 [952. 959. 952. ...   0.   0.   0.]
 [952. 959. 952. ...   0.   0.   0.]
 ...
 [946. 950. 950. ...   4.   1.  56.]
 [958. 998. 956. ...   2.   0.   0.]
 [958. 997. 956. ...   2.   0.   0.]]


In [3]:
img_array = results
print(img_array.shape)

(206, 50)


In [4]:
random.shuffle(img_array)

In [5]:
X = []
y = []
X2 = []
Y2 = []
for img in img_array:
    X.append(img[24:48].reshape(6, 4, 1))
    y.append(img[48])
    X2.append(img[24:48].reshape(6, 4, 1))
    Y2.append(img[49])
X = np.array(X)

In [6]:
X = X.astype('float32')
X /= 255
Y = np_utils.to_categorical(y, 2)
print(shape(Y))

(206, 2)


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.05, random_state = 4)

In [8]:
batch_size = 16
nb_epochs = 100

In [9]:
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(1, (2, 2), activation = tf.nn.relu, input_shape = (6, 4, 1)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(16, activation = tf.nn.relu),
    tf.keras.layers.Dense(8, activation = tf.nn.relu),
    tf.keras.layers.Dense(4, activation = tf.nn.relu),
    tf.keras.layers.Dense(2,  activation = tf.nn.softmax)
])

In [10]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 5, 3, 1)           5         
_________________________________________________________________
flatten (Flatten)            (None, 15)                0         
_________________________________________________________________
dense (Dense)                (None, 16)                256       
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 136       
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 36        
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 10        
Total params: 443
Trainable params: 443
Non-trainable params: 0
__________________________________________________________

In [10]:
model.fit(X_train, y_train, batch_size = batch_size, epochs = nb_epochs, verbose = 1, validation_data = (X_test, y_test))

Train on 195 samples, validate on 11 samples
Epoch 1/100
195/195 [==============================] - 4s 19ms/sample - loss: 0.6938 - accuracy: 0.4769 - val_loss: 0.6907 - val_accuracy: 0.6364
Epoch 2/100
195/195 [==============================] - 0s 354us/sample - loss: 0.6850 - accuracy: 0.7179 - val_loss: 0.6849 - val_accuracy: 0.6364
Epoch 3/100
195/195 [==============================] - 0s 425us/sample - loss: 0.6748 - accuracy: 0.7179 - val_loss: 0.6715 - val_accuracy: 0.6364
Epoch 4/100
195/195 [==============================] - 0s 395us/sample - loss: 0.6556 - accuracy: 0.7179 - val_loss: 0.6488 - val_accuracy: 0.6364
Epoch 5/100
195/195 [==============================] - 0s 374us/sample - loss: 0.6254 - accuracy: 0.7179 - val_loss: 0.6159 - val_accuracy: 0.6364
Epoch 6/100
195/195 [==============================] - 0s 431us/sample - loss: 0.5846 - accuracy: 0.7179 - val_loss: 0.5771 - val_accuracy: 0.6364
Epoch 7/100
195/195 [==============================] - 0s 420us/sample - l

In [11]:
model.save("body.h5")

In [11]:
model = load_model('body.h5')

In [12]:
weights = model.get_weights()
print(weights)

[array([[[[ 0.5476388]],

        [[-0.1673894]]],


       [[[ 1.0778891]],

        [[ 1.0777484]]]], dtype=float32), array([-0.01182857], dtype=float32), array([[-8.81830975e-03,  3.70428473e-01,  2.47743919e-01,
        -7.20358938e-02, -2.55622655e-01,  9.27180275e-02,
         2.63496608e-01,  9.62096378e-02,  1.32171974e-01,
        -2.51735687e-01, -2.67951876e-01, -9.40111876e-02,
        -3.09506714e-01,  4.59487326e-02,  5.16469479e-01,
        -1.58333138e-01],
       [-5.06052114e-02,  1.64783686e-01,  2.69491971e-02,
        -2.63975233e-01, -3.81805182e-01,  2.07102951e-02,
        -8.13838765e-02,  5.50492048e-01, -9.34861228e-02,
         3.72330725e-01, -2.74768323e-01,  4.76469472e-02,
         1.92635402e-01,  4.99719471e-01, -1.84042290e-01,
         2.46699750e-01],
       [ 1.19509242e-01, -9.68390480e-02,  6.53335273e-01,
         1.07094169e-01,  3.16826701e-01,  4.63698924e-01,
         3.13138664e-01, -5.26267011e-03, -1.47854492e-01,
        -2.02065408e-01,

In [13]:
weight_file = open("bodyOutput.txt", "w")

for w in weights[0:]:
    weight_file.write("{")

    if(len(w.shape) == 2):
        for i in np.array(w):
            weight_file.write("{")

            for j in np.array(i):
                weight_file.write(str(j) + ", ")
            
            weight_file.write("}, \n")
    
    else:
        for j in np.array(w):
            weight_file.write(str(j) + ", ")

    weight_file.write("}\n\n")

weight_file.flush()
weight_file.close()

In [14]:
X_test = [3,63,0,0,30,13,31,2,55,0,32,11,14,40,66,8,29,29,33,4,0,5,5,0]

In [15]:
X_test = np.array(X_test)
X_test = X_test.reshape(1, 6, 4, 1)
X_test[X_test < 0] = 0

In [16]:
X_test = X_test.astype('float32')
X_test /= 255

In [17]:
ynew = model.predict(X_test)
ynew = np.argmax(ynew)

print(ynew)

1


In [18]:
inp = model.input
outputs = [layer.output for layer in model.layers]
functor = K.function([inp, K.learning_phase()], outputs)

In [19]:
layer_outs = functor([X_test, 1])
print(layer_outs)

[array([[[[0.13501373],
         [0.309442  ],
         [0.12766185]],

        [[0.27655184],
         [0.13098784],
         [0.23518988]],

        [[0.3345264 ],
         [0.41519302],
         [0.3624688 ]],

        [[0.23713166],
         [0.29280803],
         [0.2810592 ]],

        [[0.05254781],
         [0.07105717],
         [0.07755171]]]], dtype=float32), array([[0.13501373, 0.309442  , 0.12766185, 0.27655184, 0.13098784,
        0.23518988, 0.3345264 , 0.41519302, 0.3624688 , 0.23713166,
        0.29280803, 0.2810592 , 0.05254781, 0.07105717, 0.07755171]],
      dtype=float32), array([[0.        , 0.16435738, 0.62101513, 0.        , 0.        ,
        1.1448019 , 0.        , 0.86804825, 0.        , 0.05864701,
        0.        , 0.8096873 , 0.3384188 , 1.3345646 , 0.598751  ,
        0.        ]], dtype=float32), array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        2.9303737 , 0.23620135, 3.2076278 ]], dtype=float32), array([[0.       , 4.746942

In [20]:
from keras.layers import Dense, Flatten

In [21]:
x, y = np.array(X2), np.array(Y2)
print(x.shape)

(206, 6, 4, 1)


In [22]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.05, random_state = 4)

In [23]:
model = Sequential()
model.add(Conv2D(1, 2, activation="relu", input_shape = (6, 4, 1)))
model.add(Flatten())
model.add(Dense(16, activation="relu"))
model.add(Dense(8, activation="relu"))
model.add(Dense(4, activation="relu"))
model.add(Dense(2, activation="relu"))
model.add(Dense(1))
model.compile(loss="mse", optimizer="adam")
 
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 5, 3, 1)           5         
_________________________________________________________________
flatten_1 (Flatten)          (None, 15)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 16)                256       
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 136       
_________________________________________________________________
dense_3 (Dense)              (None, 4)                 36        
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 10        
_________________________________________________________________
dense_5 (Dense)              (None, 1)                

In [24]:
model.fit(xtrain, ytrain, batch_size = 12, epochs = 1000, verbose = 1, validation_data = (xtest, ytest))

Train on 195 samples, validate on 11 samples
Epoch 1/1000
195/195 [==============================] - 1s 3ms/step - loss: 2827.2505 - val_loss: 1919.4727
Epoch 2/1000
195/195 [==============================] - 0s 328us/step - loss: 2722.0643 - val_loss: 1890.6282
Epoch 3/1000
195/195 [==============================] - 0s 410us/step - loss: 2671.5236 - val_loss: 1867.3419
Epoch 4/1000
195/195 [==============================] - 0s 369us/step - loss: 2642.3891 - val_loss: 1849.1094
Epoch 5/1000
195/195 [==============================] - 0s 410us/step - loss: 2633.7741 - val_loss: 1847.9462
Epoch 6/1000
195/195 [==============================] - 0s 369us/step - loss: 2631.4133 - val_loss: 1846.8024
Epoch 7/1000
195/195 [==============================] - 0s 451us/step - loss: 2629.1070 - val_loss: 1845.6284
Epoch 8/1000
195/195 [==============================] - 0s 451us/step - loss: 2625.6900 - val_loss: 1841.5437
Epoch 9/1000
195/195 [==============================] - 0s 451us/step - loss:

195/195 [==============================] - 0s 410us/step - loss: 13.5786 - val_loss: 12.3097
Epoch 153/1000
195/195 [==============================] - 0s 451us/step - loss: 13.5725 - val_loss: 11.3439
Epoch 154/1000
195/195 [==============================] - 0s 410us/step - loss: 14.0906 - val_loss: 8.2710
Epoch 155/1000
195/195 [==============================] - 0s 410us/step - loss: 14.9230 - val_loss: 15.3272
Epoch 156/1000
195/195 [==============================] - 0s 451us/step - loss: 13.6935 - val_loss: 14.4186
Epoch 157/1000
195/195 [==============================] - 0s 369us/step - loss: 13.2080 - val_loss: 10.7873
Epoch 158/1000
195/195 [==============================] - 0s 369us/step - loss: 13.2147 - val_loss: 15.8861
Epoch 159/1000
195/195 [==============================] - 0s 410us/step - loss: 13.2983 - val_loss: 12.0366
Epoch 160/1000
195/195 [==============================] - 0s 410us/step - loss: 13.9119 - val_loss: 11.3036
Epoch 161/1000
195/195 [====================

195/195 [==============================] - 0s 410us/step - loss: 11.3309 - val_loss: 11.3619
Epoch 304/1000
195/195 [==============================] - 0s 369us/step - loss: 10.8596 - val_loss: 15.2240
Epoch 305/1000
195/195 [==============================] - 0s 451us/step - loss: 11.3330 - val_loss: 13.2264
Epoch 306/1000
195/195 [==============================] - 0s 369us/step - loss: 11.0951 - val_loss: 11.9093
Epoch 307/1000
195/195 [==============================] - 0s 369us/step - loss: 11.0823 - val_loss: 13.9317
Epoch 308/1000
195/195 [==============================] - 0s 413us/step - loss: 10.9719 - val_loss: 12.3443
Epoch 309/1000
195/195 [==============================] - 0s 410us/step - loss: 11.5635 - val_loss: 18.8061
Epoch 310/1000
195/195 [==============================] - 0s 369us/step - loss: 11.9530 - val_loss: 18.6842
Epoch 311/1000
195/195 [==============================] - 0s 369us/step - loss: 14.5877 - val_loss: 14.9251
Epoch 312/1000
195/195 [===================

195/195 [==============================] - 0s 410us/step - loss: 10.6299 - val_loss: 7.3280
Epoch 456/1000
195/195 [==============================] - 0s 410us/step - loss: 10.0755 - val_loss: 8.9848
Epoch 457/1000
195/195 [==============================] - 0s 369us/step - loss: 9.4731 - val_loss: 11.0412
Epoch 458/1000
195/195 [==============================] - 0s 352us/step - loss: 10.1448 - val_loss: 13.2414
Epoch 459/1000
195/195 [==============================] - 0s 410us/step - loss: 10.2070 - val_loss: 10.4704
Epoch 460/1000
195/195 [==============================] - 0s 328us/step - loss: 9.8378 - val_loss: 8.0480
Epoch 461/1000
195/195 [==============================] - 0s 345us/step - loss: 9.7128 - val_loss: 11.1017
Epoch 462/1000
195/195 [==============================] - 0s 410us/step - loss: 9.4931 - val_loss: 15.9148
Epoch 463/1000
195/195 [==============================] - 0s 370us/step - loss: 11.0245 - val_loss: 12.9793
Epoch 464/1000
195/195 [==========================

195/195 [==============================] - 0s 369us/step - loss: 9.0918 - val_loss: 12.5819
Epoch 608/1000
195/195 [==============================] - 0s 451us/step - loss: 9.6346 - val_loss: 10.4570
Epoch 609/1000
195/195 [==============================] - 0s 410us/step - loss: 9.0377 - val_loss: 7.9737
Epoch 610/1000
195/195 [==============================] - 0s 410us/step - loss: 8.7802 - val_loss: 8.1057
Epoch 611/1000
195/195 [==============================] - 0s 410us/step - loss: 9.0842 - val_loss: 7.5661
Epoch 612/1000
195/195 [==============================] - 0s 369us/step - loss: 9.0495 - val_loss: 9.1510
Epoch 613/1000
195/195 [==============================] - 0s 369us/step - loss: 11.2937 - val_loss: 9.2952
Epoch 614/1000
195/195 [==============================] - 0s 369us/step - loss: 9.6305 - val_loss: 8.0967
Epoch 615/1000
195/195 [==============================] - 0s 369us/step - loss: 9.6879 - val_loss: 8.2140
Epoch 616/1000
195/195 [==============================] - 

Epoch 684/1000
195/195 [==============================] - 0s 410us/step - loss: 8.5252 - val_loss: 11.0113
Epoch 685/1000
195/195 [==============================] - 0s 369us/step - loss: 8.5604 - val_loss: 9.0861
Epoch 686/1000
195/195 [==============================] - 0s 369us/step - loss: 8.6548 - val_loss: 11.9475
Epoch 687/1000
195/195 [==============================] - 0s 328us/step - loss: 8.9308 - val_loss: 9.6562
Epoch 688/1000
195/195 [==============================] - 0s 328us/step - loss: 8.5804 - val_loss: 9.1522
Epoch 689/1000
195/195 [==============================] - 0s 369us/step - loss: 8.2397 - val_loss: 10.4363
Epoch 690/1000
195/195 [==============================] - 0s 328us/step - loss: 8.6221 - val_loss: 8.6150
Epoch 691/1000
195/195 [==============================] - 0s 328us/step - loss: 9.7775 - val_loss: 9.7109
Epoch 692/1000
195/195 [==============================] - 0s 328us/step - loss: 8.6729 - val_loss: 8.4782
Epoch 693/1000
195/195 [===================

195/195 [==============================] - 0s 410us/step - loss: 7.8423 - val_loss: 11.6747
Epoch 837/1000
195/195 [==============================] - 0s 451us/step - loss: 7.5711 - val_loss: 12.3738
Epoch 838/1000
195/195 [==============================] - 0s 369us/step - loss: 7.3891 - val_loss: 9.4626
Epoch 839/1000
195/195 [==============================] - 0s 410us/step - loss: 7.6859 - val_loss: 12.5863
Epoch 840/1000
195/195 [==============================] - 0s 451us/step - loss: 9.1291 - val_loss: 11.2678
Epoch 841/1000
195/195 [==============================] - 0s 369us/step - loss: 7.2673 - val_loss: 14.0693
Epoch 842/1000
195/195 [==============================] - 0s 369us/step - loss: 7.9836 - val_loss: 13.8527
Epoch 843/1000
195/195 [==============================] - 0s 369us/step - loss: 7.4707 - val_loss: 12.0435
Epoch 844/1000
195/195 [==============================] - 0s 410us/step - loss: 8.2931 - val_loss: 10.6095
Epoch 845/1000
195/195 [=============================

Epoch 913/1000
195/195 [==============================] - 0s 410us/step - loss: 7.5621 - val_loss: 11.7591
Epoch 914/1000
195/195 [==============================] - 0s 451us/step - loss: 7.1445 - val_loss: 10.9165
Epoch 915/1000
195/195 [==============================] - 0s 369us/step - loss: 6.7299 - val_loss: 10.4450
Epoch 916/1000
195/195 [==============================] - 0s 328us/step - loss: 7.5996 - val_loss: 9.2389
Epoch 917/1000
195/195 [==============================] - 0s 369us/step - loss: 8.3471 - val_loss: 10.9150
Epoch 918/1000
195/195 [==============================] - 0s 369us/step - loss: 7.2080 - val_loss: 10.9640
Epoch 919/1000
195/195 [==============================] - 0s 372us/step - loss: 6.7103 - val_loss: 10.2514
Epoch 920/1000
195/195 [==============================] - 0s 369us/step - loss: 7.5214 - val_loss: 11.7004
Epoch 921/1000
195/195 [==============================] - 0s 410us/step - loss: 7.2077 - val_loss: 11.8232
Epoch 922/1000
195/195 [==============

In [25]:
model.save("weight.h5")

In [24]:
model = load_model('weight.h5')

In [25]:
weights = model.get_weights()
print(weights)

[array([[[[-0.00401282]],

        [[ 0.4033855 ]]],


       [[[ 0.4789799 ]],

        [[ 0.732079  ]]]], dtype=float32), array([0.5592655], dtype=float32), array([[ 1.45019218e-01,  1.99813679e-01, -6.84632212e-02,
         5.16810417e-01,  3.97849619e-01, -3.04727882e-01,
         3.07735145e-01, -5.76841295e-01,  8.70705917e-02,
        -1.34409666e-01,  6.97031245e-02,  2.98576474e-01,
         5.26757613e-02, -6.38653338e-01, -1.42709783e-03,
         3.54696900e-01],
       [ 1.30236641e-01, -2.43810758e-01, -5.70605576e-01,
         3.38256985e-01,  2.98650742e-01,  1.77447200e-01,
         5.93336284e-01,  1.74957111e-01,  3.25756669e-01,
        -2.67350584e-01, -3.82977962e-01, -2.57518947e-01,
        -5.47694862e-01,  2.49703676e-01, -4.29727823e-01,
        -6.57711446e-01],
       [ 2.22981200e-01,  3.31233948e-01,  4.63645816e-01,
         3.84424478e-01, -2.31719375e-01, -5.80937266e-01,
         1.74304396e-01, -8.37390274e-02,  4.72448438e-01,
         7.65425339e-0

In [26]:
weight_file = open("weightOutput.txt", "w")

for w in weights[0:]:
    weight_file.write("{")

    if(len(w.shape) == 2):
        for i in np.array(w):
            weight_file.write("{")

            for j in np.array(i):
                weight_file.write(str(j) + ", ")
            
            weight_file.write("}, \n")
    
    else:
        for j in np.array(w):
            weight_file.write(str(j) + ", ")
    
    weight_file.write("}\n\n")

weight_file.flush()
weight_file.close()

In [27]:
X_test = [3,63,0,0,30,13,31,2,55,0,32,11,14,40,66,8,29,29,33,4,0,5,5,0]

In [28]:
X_test = np.array(X_test)
X_test = X_test.reshape(1, 6, 4, 1)
X_test[X_test < 0] = 0

In [29]:
ynew = model.predict(X_test)
print(ynew)

[[42.869347]]


In [30]:
inp = model.input
outputs = [layer.output for layer in model.layers]
functor = K.function([inp, K.learning_phase()], outputs)

In [31]:
layer_outs = functor([X_test, 1])
print(layer_outs)

[array([[[[49.846935 ],
         [29.227646 ],
         [16.8718   ]],

        [[32.026787 ],
         [36.43858  ],
         [24.621864 ]],

        [[36.32744  ],
         [80.944016 ],
         [42.337402 ]],

        [[51.759212 ],
         [65.07122  ],
         [22.256155 ]],

        [[15.801467 ],
         [19.80991  ],
         [ 4.4352837]]]], dtype=float32), array([[49.846935 , 29.227646 , 16.8718   , 32.026787 , 36.43858  ,
        24.621864 , 36.32744  , 80.944016 , 42.337402 , 51.759212 ,
        65.07122  , 22.256155 , 15.801467 , 19.80991  ,  4.4352837]],
      dtype=float32), array([[59.09113  , 59.31321  ,  0.       , 78.81842  ,  3.3880386,
         0.       , 42.616882 ,  0.       ,  0.       ,  0.       ,
         0.       , 51.249973 ,  0.       ,  0.       ,  0.       ,
         0.       ]], dtype=float32), array([[97.16315 , 19.86484 ,  0.      ,  0.      ,  0.      ,  0.      ,
         0.      , 46.372894]], dtype=float32), array([[77.8156  , 35.36715 , 50.36

In [32]:
i = 0
correct = 0

for x in xtrain:
    x = x.reshape(1, 6, 4, 1)
    ynew = model.predict(x)
    
    if(abs(ytrain[i] - ynew) <= 5):
        correct += 1
    
    i += 1
    
accuracy = (correct / xtrain.shape[0])
print('Training Accuracy:', accuracy)

i = 0
correct = 0

for x in xtest:
    x = x.reshape(1, 6, 4, 1)
    ynew = model.predict(x)
    
    if(abs(ytest[i] - ynew) <= 5):
        correct += 1
    
    i += 1

accuracy = (correct / xtest.shape[0])
print('Validation Accuracy:', accuracy)

Training Accuracy: 0.9794871794871794
Validation Accuracy: 0.9090909090909091
